import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import NavBar from "./NavBar.jsx";
import Image from "next/image";
// import mtWashington from '../../public/mt-washington-view-rocks.jpg';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Explore Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      

      <Image 
      src="/mt-washington-view-rocks.jpg" 
      width={800} 
  height={600}
  layout="responsive"
  alt="Hiking Mt. Washington"/>
        <button type="button" className="btn btn-success">Learn more about Jessica!</button>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >




        <footer></footer>
      </div>
    </>
  );
}
