import Head from "next/head";
import Image from "next/image";
import Link from "next/link"; // Import Link from next/link
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
//import AboutMe from "./AboutMe.js"; // Import the AboutMe component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Explore Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <nav>
          <Link href="/AboutMe">
            <div>About Me</div>
          </Link>
          <a
            href="/AboutMe"
            target="_blank"
            rel="noopener noreferrer"
          >
            About me
          </a>
        </nav>
        <main >
          
        
        </main>

        <footer>
          
        </footer>
      </div>
    </>
  );
}
